### ISSUE TITLE
Create butler character styled similar to Brawlhalla

### ISSUE THREAD

**Issue by NDGogo** [NDGogo/fizz#36]

**Comment by Tirivitive** [comment]
![image](https://user-images.githubusercontent.com/9106143/126944329-04672801-7236-4577-a3ba-695ba4b1e88b.png)

**Comment by Tirivitive** [comment]
![MMM-Sebastian](https://user-images.githubusercontent.com/9106143/126949243-f71c31b4-f0c0-4262-91ad-1a7745a6df94.png)

**Comment by Tirivitive** [comment]
![MMM-Sebastian](https://user-images.githubusercontent.com/9106143/126950415-89036937-02b9-41a1-83c5-9e91d4419b2e.png)

**Comment by Tirivitive** [comment]
![MMM-Sebastian-transparent](https://user-images.githubusercontent.com/9106143/126951069-59e9bd8b-1b04-4fd1-8e6b-f96bec2376e7.png)
![MMM-Sebastian](https://user-images.githubusercontent.com/9106143/126951078-7950ce04-9847-4dcf-96b9-eca011ff2a77.png)
